heroBackgroundImage: /images/hero-bg.png
heroLogoImage: /images/logo-cream.png
sunburstImage: /images/sunburst.png
reservationUrl: >-
  https://www.covermanager.com/reserve/module_restaurant/restaurante-guepardo/spanish
reservationsBgImage: /images/reservations-bg.png
guepardoBannerImage: /images/guepardo-banner.png
address: "São Paulo 2367-int. 6, Providencia, 44630 Guadalajara, Jal."
whatsappUrl: "https://wa.me/523320559502"
instagramUrl: "https://www.instagram.com/guepardo.mx/"
googleMapsUrl: "https://share.google/5w7rQSpzuIE2nsGY2"
mandalaGroupUrl: "https://mandalagroup.mx/"
mandalaGroupLogo: /images/mandala-group-logo.png
copyright: "Copyright ® 2024 Mandala Group."
