siteName: Tacos Atarantados
tagline: Tacos norteños, bien servidos.
favicon: ~
ogImage: ~
facebookUrl: https://www.facebook.com/TacosAtarantados/?locale=es_LA
instagramUrl: https://www.instagram.com/tacosatarantados/?hl=es
tiktokUrl: https://www.tiktok.com/@tacosatarantados?lang=es
twitterUrl: https://x.com/atarantados
